Update tubemq_user_guide.md
Tencent/TubeMQ pull request #61
Opened 2019-10-07 08:05 UTC by JunpingDu

Make some minor changes to document, fix some issues of grammar and expression.

This issue get reported via: https://github.com/Tencent/TubeMQ/issues/60

2019-10-07 08:21 UTC, tisonkun requested changes
Thanks for your contribution @JunpingDu! I left several inline comments.

2019-10-07 08:21 UTC, TisonKun commented on docs/tubemq_user_guide.md
> +In above example, we run the services on a single node. However, in the real production environment, you may
```suggestion
In the example above, we run the services on a single node. However, in real production environment, you
```

2019-10-07 08:21 UTC, TisonKun commented on docs/tubemq_user_guide.md
>  need to run multiple master services on different servers for high availability purpose. Here's
```suggestion
need to run multiple master services on different servers to enable high availability. Here's
```

2019-10-07 08:21 UTC, TisonKun commented on docs/tubemq_user_guide.md
> +- Java 7/8(Java 9+ are not verified yet)
```suggestion
- Java 1.7 or 1.8(Java 9 and above haven't been verified yet)
```

2019-10-07 17:14 UTC, JunpingDu reviewed
Thanks for comment, Tison. Latest PR should address your comments.

2019-10-08 00:37 UTC, tisonkun approved these changes
Thanks for your updates @JunpingDu ! LTGM.

Merging...

2019-10-08 00:37 UTC, merged